spring.application.name=BankCardManagementSystemApi

server.port=8087
spring.liquibase.change-log=classpath:db/migration/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://localhost:5438/postgres
spring.datasource.username=postgres
spring.datasource.password=54321
spring.datasource.driver-class-name=org.postgresql.Driver
